### ISSUE TITLE
issue in the first sql

### ISSUE THREAD

**Issue by MapleArea** [v3921358/LithiumREV96#2]
שגיאה
שאילתת SQL: [העתקה](http://localhost/phpmyadmin/index.php?route=/import#)

CREATE TABLE `csequipment` (
  `inventoryequipmentid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `inventoryitemid` bigint(20) unsigned NOT NULL DEFAULT '0',
  `upgradeslots` int(11) NOT NULL DEFAULT '0',
  `level` int(11) NOT NULL DEFAULT '0',
  `str` int(11) NOT NULL DEFAULT '0',
  `dex` int(11) NOT NULL DEFAULT '0',
  `int` int(11) NOT NULL DEFAULT '0',
  `luk` int(11) NOT NULL DEFAULT '0',
  `hp` int(11) NOT NULL DEFAULT '0',
  `mp` int(11) NOT NULL DEFAULT '0',
  `watk` int(11) NOT NULL DEFAULT '0',
  `matk` int(11) NOT NULL DEFAULT '0',
  `wdef` int(11) NOT NULL DEFAULT '0',
  `mdef` int(11) NOT NULL DEFAULT '0',
  `acc` int(11) NOT NULL DEFAULT '0',
  `avoid` int(11) NOT NULL DEFAULT '0',
  `hands` int(11) NOT NULL DEFAULT '0',
  `speed` int(11) NOT NULL DEFAULT '0',
  `jump` int(11) NOT NULL DEFAULT '0',
  `ViciousHammer` tinyint(2) NOT NULL DEFAULT '0',
  `itemEXP` int(11) NOT NULL DEFAULT '0',
  `durability` int(11) NOT NULL DEFAULT '-1',
  `enhance`[...]
MySQL אמר: תיעוד

#1005 - Can't create table `lithium`.`csequipment` (errno: 140 "Wrong create options") ([Details…](http://localhost/phpmyadmin/index.php?route=/server/engines/InnoDB/Status))

what i do worng? i use xammp

**Comment by MapleArea** [comment]
all the sql have issue's while running them

**Comment by v3921358** [comment]
[fix](https://github.com/v3921358/LithiumREV96/commit/d6cefb516392fb7098ac38a87e8f5bfa369c677b)
