### ISSUE TITLE
issue on lunch

### ISSUE THREAD

**Issue by MapleArea** [v3921358/LithiumREV96#3]
![image](https://github.com/v3921358/LithiumREV96/assets/141136821/7e78e060-f2f3-4309-acca-5ab935792ea6)

Hey agian and thx you for answering me!
i dont know maybe im do something wrong but im compile im use the tut of ragezone also change the bat file us ragezone tut.
any idea what worng?

**Comment by MapleArea** [comment]
nvm my foult im fixed it. :S

**Comment by v3921358** [comment]
46c2ed980244bdca7f0fed1854cb1735a7c3d02e
